name: Update Website
on:
    push:
      branches: [master]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing host server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: 140.82.44.145
        username: fandemic
        key: ${{ secrets.SERVER_SSH_SECRET  }}
        port: 22
        script: | 
          cd backlogburner
          git pull origin master
          npm run build
          sudo rm /var/www/html/* -r
          sudo cp dist/* /var/ww/html -fpr
