name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Connect to server
      uses: appleboy/ssh-action@master
      with:
        host: 140.82.44.145
        username: fandemic
        key: ${{ secrets.SERVER_SSH_SECRET  }}
        port: 22
        script: | 
          killall api_backend
          echo "API KILLED"
          cd backlogburner/api_backend
          echo "Building API"
          /home/fandemic/.cargo/bin/cargo build --release
          cd target/release
          echo "Running API"
          ./api_backend &
          echo "Done"
