name: Update Website
on:
    push:
      branches: [master]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Update Frontend
      uses: appleboy/ssh-action@master
      with:
        host: 140.82.44.145
        username: fandemic
        key: ${{ secrets.SERVER_SSH_SECRET  }}
        port: 22
        script: | 
          cd backlogburner
          git pull origin master
          npm install
          npm run build
          sudo rm -rf /var/www/html/* 
          sudo cp dist/* /var/www/html -fpr
